feat(coding-style): Added parameter for `checker` script

diff --git a/checker b/checker
--- a/checker
+++ b/checker
@@ -1,5 +1,14 @@
 #!/bin/bash
 
-FILES=$(find . -iname "*.cpp" -or -iname "*.hpp" | xargs)
+FILES=$(find $1 -iname "*.cpp" -or -iname "*.hpp" | xargs)
+CMD="clang-format --dry-run $FILES |& grep violations | wc -l"
+RET=$(eval "$CMD")
 
-clang-format --dry-run "$FILES"
+if [ "$RET" = 0 ]; then # grep failed -> no lines were returned by clang-format
+  exit 0;
+else
+  echo "After running $CMD"
+  echo "$RET errors found in $(echo "$FILES" | wc -w) files. Commit aborted..."
+  exit 1;
+fi
+
